package com.andrei.template.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import com.andrei.template.database.Table_WhatsMyIpPOJODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig table_WhatsMyIpPOJODaoConfig;

    private final Table_WhatsMyIpPOJODao table_WhatsMyIpPOJODao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        table_WhatsMyIpPOJODaoConfig = daoConfigMap.get(Table_WhatsMyIpPOJODao.class).clone();
        table_WhatsMyIpPOJODaoConfig.initIdentityScope(type);

        table_WhatsMyIpPOJODao = new Table_WhatsMyIpPOJODao(table_WhatsMyIpPOJODaoConfig, this);

        registerDao(Table_WhatsMyIpPOJO.class, table_WhatsMyIpPOJODao);
    }
    
    public void clear() {
        table_WhatsMyIpPOJODaoConfig.getIdentityScope().clear();
    }

    public Table_WhatsMyIpPOJODao getTable_WhatsMyIpPOJODao() {
        return table_WhatsMyIpPOJODao;
    }

}
