package com.andrei.template.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.Date;

/**
 * Entity mapped to table "Table_WhatsMyIpPOJO".
 */
public class Table_WhatsMyIpPOJO {

    private Long id;
    private String YourFuckingIPAddress;
    private String YourFuckingLocation;
    private String YourFuckingHostname;
    private String YourFuckingISP;
    private java.util.Date date;

    public Table_WhatsMyIpPOJO(String yourFuckingIPAddress, String yourFuckingLocation, String yourFuckingHostname, String yourFuckingISP, Date date) {
        YourFuckingIPAddress = yourFuckingIPAddress;
        YourFuckingLocation = yourFuckingLocation;
        YourFuckingHostname = yourFuckingHostname;
        YourFuckingISP = yourFuckingISP;
        this.date = date;
    }

    public Table_WhatsMyIpPOJO() {
    }

    public Table_WhatsMyIpPOJO(Long id) {
        this.id = id;
    }

    public Table_WhatsMyIpPOJO(Long id, String YourFuckingIPAddress, String YourFuckingLocation, String YourFuckingHostname, String YourFuckingISP, java.util.Date date) {
        this.id = id;
        this.YourFuckingIPAddress = YourFuckingIPAddress;
        this.YourFuckingLocation = YourFuckingLocation;
        this.YourFuckingHostname = YourFuckingHostname;
        this.YourFuckingISP = YourFuckingISP;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getYourFuckingIPAddress() {
        return YourFuckingIPAddress;
    }

    public void setYourFuckingIPAddress(String YourFuckingIPAddress) {
        this.YourFuckingIPAddress = YourFuckingIPAddress;
    }

    public String getYourFuckingLocation() {
        return YourFuckingLocation;
    }

    public void setYourFuckingLocation(String YourFuckingLocation) {
        this.YourFuckingLocation = YourFuckingLocation;
    }

    public String getYourFuckingHostname() {
        return YourFuckingHostname;
    }

    public void setYourFuckingHostname(String YourFuckingHostname) {
        this.YourFuckingHostname = YourFuckingHostname;
    }

    public String getYourFuckingISP() {
        return YourFuckingISP;
    }

    public void setYourFuckingISP(String YourFuckingISP) {
        this.YourFuckingISP = YourFuckingISP;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    @Override public String toString() {
        return "Table_WhatsMyIpPOJO{" +
                "id=" + id +
                ", YourFuckingIPAddress='" + YourFuckingIPAddress + '\'' +
                ", YourFuckingLocation='" + YourFuckingLocation + '\'' +
                ", YourFuckingHostname='" + YourFuckingHostname + '\'' +
                ", YourFuckingISP='" + YourFuckingISP + '\'' +
                ", date=" + date +
                '}';
    }
}
